services:
  arqan.front:
    image: veridevops/arqan.streamlit-front:migration
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
    ports:
      - "8501:8501"
    deploy:
      resources:
        limits:
          memory: 200M
